name: Playwright Tests - Docker Container

on:
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Docker'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - name: Run your tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
        env:
          HOME: /root
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Test Results                # Name of the check run which will be created
          path: reports/test-results.trx    # Path to test results
          reporter: dotnet-trx              # Format of test results
